name: 🚀 CI - Train ML model with MLflow Project

on:
  workflow_dispatch:
  push: # agar bisa dijalankan manual

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: sentiment-env
          auto-activate-base: false

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow project
        run: mlflow run MLProject -P data_path=amazon_cleaned_preprocessing.csv

      - name: Upload artefak model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: mlruns
