name: Preprocess Amazon Dataset

on:
  workflow_dispatch:
    paths:
      - Eksperimen_SML_kenbamaulana/preprocessing/**.py
      - .github/workflows/**

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: |
        python Eksperimen_SML_kenbamaulana/preprocessing/automate_kenbamaulana.py

    - name: Upload processed dataset as artifact
      uses: actions/upload-artifact@v4
      with:
        name: amazon_cleaned_preprocessing
        path: amazon_cleaned_preprocessing.csv
